

server:
 port: 8088
 
 
spring:
 application:
  name: gateway-app
 cloud:
  gateway:
   routes:
    - id: client1
      uri: lb://eureka-client
      predicates:
       - Path=/test
    - id: client2
      uri: lb://eureka-client-2
      predicates:
       - Path=/client2  
